package shared;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * It is responsible for providing a common interface to implement 
 * any of the algorithms.
 * 
 * @author Cluster 7 sub 3
 * @version 1.0
 */
public abstract class Algorithm
{
    /**
     * Allows pass other params into class
     * @param options
     */
    public abstract void options(ArrayList<Integer> options);
    /**
     * Generate the solution 
     * @param g Graph
     */
    public abstract void calc(Graph g);
    /**
     * Select solution for the user
     * @param p Integer between 0 and 100
     * @return Correct graph solution for user.
     */
    public abstract Graph obtain(Integer p);
    /**
     * Select all graph generated by applied algorithm
     * @return All graph solution for user.
     */
    public abstract HashMap obtainAll();
}
