package shared;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * Class for applying the Louvain algorithm to a graph
 * @author Cluster 7 sub 3
 * @version 1.0
 */
public class Louvain extends Algorithm
{
    public Louvain(){}
    /**
     * Allows pass other params into class
     * @param options
     */
    @Override
    public void options(ArrayList<Integer> options){}
    /**
     * Apply the Louvain algorithm
     * @param g Grafo
     */
    @Override
    public void calc(Graph g){}
    /**
     * Select solution for the user
     * @param p Integer between 0 and 100
     * @return Correct graph solution for user.
     */
    @Override
    public Graph obtain(Integer p){return new Graph();}
    /**
     * Select all graph generated by applied algorithm
     * @return All graph solution for user.
     */
    @Override
    public HashMap obtainAll(){return new HashMap();}
}