/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Joan Rodas
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    // Controlador de presentacion
  private final CtrlPresentacion iCtrlPresentacion;

 //   /**
 //    * Creates new form Ventana
 //    */
  //  public VistaPrincipal() {
  //      initComponents();
  //  }
    
     public VistaPrincipal (CtrlPresentacion pCtrlPresentacion) {
    System.out.println
      ("isEventDispatchThread: " + SwingUtilities.isEventDispatchThread());
    iCtrlPresentacion = pCtrlPresentacion;
    
    this.setMinimumSize(new Dimension(1200,520));
    this.setPreferredSize(this.getMinimumSize());
    this.setResizable(false);
    // Posicion y operaciones por defecto
    this.setLocationRelativeTo(null);
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    initComponents();
  }

  public void hacerVisible() {
    System.out.println
      ("isEventDispatchThread: " + SwingUtilities.isEventDispatchThread());
    
    this.pack();
    this.setVisible(true);
  }

  public void activar() {
    this.setEnabled(true);
  }

  public void desactivar() {
    this.setEnabled(false);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoAlgoritmos = new javax.swing.ButtonGroup();
        tabsPrincipal = new javax.swing.JTabbedPane();
        panelImportar = new javax.swing.JPanel();
        btnImportarGrafo = new javax.swing.JButton();
        btnImportarConj = new javax.swing.JButton();
        btnNuevoGrafo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelGrafo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCatToAddRmv = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPagToAddRmv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNodo1Enlace = new javax.swing.JTextField();
        btnAddCatToGraph = new javax.swing.JButton();
        btnRmvCatFromGraph = new javax.swing.JButton();
        btnAddLinkToGraph = new javax.swing.JButton();
        btnAddPagToGraph = new javax.swing.JButton();
        btnRmvPagFromGraph = new javax.swing.JButton();
        btnRmvLinkFromGraph = new javax.swing.JButton();
        txtNodo2Enlace = new javax.swing.JTextField();
        comboTipoEnlace = new javax.swing.JComboBox();
        btnChangeName = new javax.swing.JButton();
        btnListCatGraph = new javax.swing.JButton();
        btnListPagGraph = new javax.swing.JButton();
        btnListLinksGraph = new javax.swing.JButton();
        btnExportarGrafo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtListGraph = new javax.swing.JTextArea();
        txtNombreNodoAnterior = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNombreNodoNuevo = new javax.swing.JTextField();
        btnImportarGrafo1 = new javax.swing.JButton();
        btnNuevoGrafo1 = new javax.swing.JButton();
        comboTipoNodo = new javax.swing.JComboBox();
        panelAlgoritmo = new javax.swing.JPanel();
        radioGirvan = new javax.swing.JRadioButton();
        radioLouvain = new javax.swing.JRadioButton();
        radioClique = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtValorP = new javax.swing.JTextField();
        btnEjecutar = new javax.swing.JButton();
        tabsAlgoritmo = new javax.swing.JTabbedPane();
        tabSelPag = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPaginas = new javax.swing.JList();
        ckTodasPaginas = new javax.swing.JCheckBox();
        btnAplicarSelPag = new javax.swing.JButton();
        tabSelCat = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listCategorias = new javax.swing.JList();
        ckTodasCategorias = new javax.swing.JCheckBox();
        btnAplicarSelCat = new javax.swing.JButton();
        tabFiltros = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        spNombre = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spPagComun = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spCatComun = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        spSuperComun = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        spSubComun = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        btnAplicarFiltros = new javax.swing.JButton();
        panelComunidades = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtAddRmvCom = new javax.swing.JTextField();
        btnAddCatToCom = new javax.swing.JButton();
        btnRmvCatFromCom = new javax.swing.JButton();
        btnAddComToSet = new javax.swing.JButton();
        btnRmvComFromSet = new javax.swing.JButton();
        btnListComFromSet = new javax.swing.JButton();
        btnShowSet = new javax.swing.JButton();
        btnExportSet = new javax.swing.JButton();
        txtCatAddRmvSet = new javax.swing.JTextField();
        txtComToAddRmvCat = new javax.swing.JTextField();
        txtComToList = new javax.swing.JTextField();
        btnListCatFromCom = new javax.swing.JButton();
        comboTipoSet = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNombreAnterior = new javax.swing.JTextField();
        txtNombreNuevo = new javax.swing.JTextField();
        btnChangeNameSet = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnShowCom = new javax.swing.JButton();
        comboTipoNombreSet = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtListSet = new javax.swing.JTextArea();
        panelComparacion = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtListGraph1 = new javax.swing.JTextArea();
        btnCompararComunidades = new javax.swing.JButton();
        comboTipoCom1 = new javax.swing.JComboBox();
        comboTipoCom2 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnCompararConjuntos = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menuFichero = new javax.swing.JMenu();
        mItemImportarGrafo = new javax.swing.JMenuItem();
        mItemImportarSet = new javax.swing.JMenuItem();
        mItemExportarGrafo = new javax.swing.JMenuItem();
        mItemExportarSet = new javax.swing.JMenuItem();
        mItemSalir = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        mItemNuevoGrafo = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        mItemManual = new javax.swing.JMenuItem();
        mItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wiki");
        setMinimumSize(new java.awt.Dimension(900, 520));
        setPreferredSize(new java.awt.Dimension(996, 520));
        setResizable(false);

        btnImportarGrafo.setText("Importar grafo");
        btnImportarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarGrafoActionPerformed(evt);
            }
        });

        btnImportarConj.setText("Importar Conjunto");
        btnImportarConj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarConjActionPerformed(evt);
            }
        });

        btnNuevoGrafo.setText("Nuevo Grafo");
        btnNuevoGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoGrafoActionPerformed(evt);
            }
        });

        jLabel11.setText("Grafo:");

        jLabel12.setText("Conjunto:");

        javax.swing.GroupLayout panelImportarLayout = new javax.swing.GroupLayout(panelImportar);
        panelImportar.setLayout(panelImportarLayout);
        panelImportarLayout.setHorizontalGroup(
            panelImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImportarGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImportarConj, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(772, Short.MAX_VALUE))
        );
        panelImportarLayout.setVerticalGroup(
            panelImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImportarGrafo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevoGrafo)
                .addGap(36, 36, 36)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImportarConj)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        tabsPrincipal.addTab("Inicio", panelImportar);

        panelGrafo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setText("Categoria:");

        txtCatToAddRmv.setToolTipText("");
        txtCatToAddRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCatToAddRmvActionPerformed(evt);
            }
        });

        jLabel9.setText("Página:");

        txtPagToAddRmv.setText("Nombre página");
        txtPagToAddRmv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPagToAddRmvFocusGained(evt);
            }
        });

        jLabel10.setText("Enlace:");

        txtNodo1Enlace.setText("Nombre nodo1");

        btnAddCatToGraph.setText("+");
        btnAddCatToGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCatToGraphActionPerformed(evt);
            }
        });

        btnRmvCatFromGraph.setText("-");
        btnRmvCatFromGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvCatFromGraphActionPerformed(evt);
            }
        });

        btnAddLinkToGraph.setText("+");
        btnAddLinkToGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLinkToGraphActionPerformed(evt);
            }
        });

        btnAddPagToGraph.setText("+");
        btnAddPagToGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPagToGraphActionPerformed(evt);
            }
        });

        btnRmvPagFromGraph.setText("-");
        btnRmvPagFromGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvPagFromGraphActionPerformed(evt);
            }
        });

        btnRmvLinkFromGraph.setText("-");
        btnRmvLinkFromGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvLinkFromGraphActionPerformed(evt);
            }
        });

        txtNodo2Enlace.setText("Nombre nodo2");

        comboTipoEnlace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CsubC", "CsupC", "CP", "PC" }));
        comboTipoEnlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoEnlaceActionPerformed(evt);
            }
        });

        btnChangeName.setText("OK");
        btnChangeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeNameActionPerformed(evt);
            }
        });

        btnListCatGraph.setText("Categorias");
        btnListCatGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCatGraphActionPerformed(evt);
            }
        });

        btnListPagGraph.setText("Páginas");
        btnListPagGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPagGraphActionPerformed(evt);
            }
        });

        btnListLinksGraph.setText("Enlaces");
        btnListLinksGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListLinksGraphActionPerformed(evt);
            }
        });

        btnExportarGrafo.setText("Exportar");
        btnExportarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarGrafoActionPerformed(evt);
            }
        });

        txtListGraph.setColumns(20);
        txtListGraph.setRows(5);
        jScrollPane4.setViewportView(txtListGraph);

        txtNombreNodoAnterior.setText("Anterior");

        jLabel13.setText("AÑADIR/QUITAR");

        jLabel14.setText("CAMBIAR NOMBRE NODO");

        txtNombreNodoNuevo.setText("Nuevo");

        btnImportarGrafo1.setText("Importar grafo");
        btnImportarGrafo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarGrafo1ActionPerformed(evt);
            }
        });

        btnNuevoGrafo1.setText("Nuevo Grafo");
        btnNuevoGrafo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoGrafo1ActionPerformed(evt);
            }
        });

        comboTipoNodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Página", "Categoria" }));
        comboTipoNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoNodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGrafoLayout = new javax.swing.GroupLayout(panelGrafo);
        panelGrafo.setLayout(panelGrafoLayout);
        panelGrafoLayout.setHorizontalGroup(
            panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrafoLayout.createSequentialGroup()
                .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGrafoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreNodoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelGrafoLayout.createSequentialGroup()
                                .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelGrafoLayout.createSequentialGroup()
                                        .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNodo2Enlace, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNodo1Enlace, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboTipoEnlace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelGrafoLayout.createSequentialGroup()
                                        .addComponent(txtCatToAddRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddCatToGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRmvCatFromGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelGrafoLayout.createSequentialGroup()
                                        .addComponent(txtPagToAddRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddPagToGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRmvPagFromGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelGrafoLayout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnAddLinkToGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombreNodoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnChangeName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnRmvLinkFromGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(panelGrafoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnImportarGrafo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevoGrafo1))
                    .addGroup(panelGrafoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExportarGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGrafoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comboTipoNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 42, Short.MAX_VALUE)
                .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelGrafoLayout.createSequentialGroup()
                        .addComponent(btnListCatGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnListPagGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnListLinksGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4))
                .addGap(25, 25, 25))
        );
        panelGrafoLayout.setVerticalGroup(
            panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrafoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListCatGraph)
                    .addComponent(btnListPagGraph)
                    .addComponent(btnListLinksGraph)
                    .addComponent(btnImportarGrafo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoGrafo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGrafoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel13)
                        .addGap(21, 21, 21)
                        .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGrafoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel10))
                            .addGroup(panelGrafoLayout.createSequentialGroup()
                                .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCatToAddRmv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddCatToGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRmvCatFromGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPagToAddRmv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAddPagToGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnRmvPagFromGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNodo1Enlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboTipoEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNodo2Enlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddLinkToGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRmvLinkFromGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55)
                        .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGrafoLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombreNodoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnChangeName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreNodoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTipoNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExportarGrafo))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabsPrincipal.addTab("Grafo", panelGrafo);

        grupoAlgoritmos.add(radioGirvan);
        radioGirvan.setText("Girvan-Newman");
        radioGirvan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGirvanActionPerformed(evt);
            }
        });

        grupoAlgoritmos.add(radioLouvain);
        radioLouvain.setSelected(true);
        radioLouvain.setText("Louvain");

        grupoAlgoritmos.add(radioClique);
        radioClique.setText("K-Clique");

        jLabel1.setText("Valor P:");

        txtValorP.setText("1");
        txtValorP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorPActionPerformed(evt);
            }
        });

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        tabsAlgoritmo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabsAlgoritmo.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabsAlgoritmo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        listPaginas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Pag1", "Pag2", "Pag3", "Pag4", "Pag5", "Pag6" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPaginas);

        ckTodasPaginas.setText("Seleccionar todas");
        ckTodasPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckTodasPaginasActionPerformed(evt);
            }
        });

        btnAplicarSelPag.setText("Aplicar");
        btnAplicarSelPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarSelPagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabSelPagLayout = new javax.swing.GroupLayout(tabSelPag);
        tabSelPag.setLayout(tabSelPagLayout);
        tabSelPagLayout.setHorizontalGroup(
            tabSelPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSelPagLayout.createSequentialGroup()
                .addContainerGap(398, Short.MAX_VALUE)
                .addGroup(tabSelPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabSelPagLayout.createSequentialGroup()
                        .addComponent(ckTodasPaginas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAplicarSelPag, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tabSelPagLayout.setVerticalGroup(
            tabSelPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabSelPagLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(tabSelPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAplicarSelPag)
                    .addComponent(ckTodasPaginas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabsAlgoritmo.addTab("Selección Páginas", tabSelPag);

        listCategorias.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Cat1", "Cat2", "Cat3", "Cat4", "Cat5", "Cat6" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listCategorias);

        ckTodasCategorias.setText("Seleccionar todas");
        ckTodasCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckTodasCategoriasActionPerformed(evt);
            }
        });

        btnAplicarSelCat.setText("Aplicar");
        btnAplicarSelCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarSelCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabSelCatLayout = new javax.swing.GroupLayout(tabSelCat);
        tabSelCat.setLayout(tabSelCatLayout);
        tabSelCatLayout.setHorizontalGroup(
            tabSelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSelCatLayout.createSequentialGroup()
                .addContainerGap(398, Short.MAX_VALUE)
                .addGroup(tabSelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabSelCatLayout.createSequentialGroup()
                        .addComponent(ckTodasCategorias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAplicarSelCat, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tabSelCatLayout.setVerticalGroup(
            tabSelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabSelCatLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(tabSelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAplicarSelCat)
                    .addComponent(ckTodasCategorias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabsAlgoritmo.addTab("Selección Categorias", tabSelCat);

        jLabel2.setText("Nombre similar:");

        spNombre.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));

        jLabel3.setText("Páginas en común:");

        spPagComun.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));

        jLabel4.setText("Categorias en común:");

        spCatComun.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));

        jLabel5.setText("SuperCat. en común:");

        spSuperComun.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));

        jLabel6.setText("SubCat. en común:");

        spSubComun.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));

        jLabel7.setText("Prioridad");

        btnAplicarFiltros.setText("Aplicar");
        btnAplicarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabFiltrosLayout = new javax.swing.GroupLayout(tabFiltros);
        tabFiltros.setLayout(tabFiltrosLayout);
        tabFiltrosLayout.setHorizontalGroup(
            tabFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFiltrosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(tabFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(tabFiltrosLayout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spPagComun))
                        .addGroup(tabFiltrosLayout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spCatComun))
                        .addGroup(tabFiltrosLayout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spSuperComun))
                        .addGroup(tabFiltrosLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spSubComun))
                        .addGroup(tabFiltrosLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spNombre))))
                    .addComponent(btnAplicarFiltros))
                .addContainerGap(567, Short.MAX_VALUE))
        );
        tabFiltrosLayout.setVerticalGroup(
            tabFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFiltrosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spPagComun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(tabFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spCatComun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(tabFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spSuperComun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(tabFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spSubComun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addComponent(btnAplicarFiltros)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        tabsAlgoritmo.addTab("Filtros", tabFiltros);

        javax.swing.GroupLayout panelAlgoritmoLayout = new javax.swing.GroupLayout(panelAlgoritmo);
        panelAlgoritmo.setLayout(panelAlgoritmoLayout);
        panelAlgoritmoLayout.setHorizontalGroup(
            panelAlgoritmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlgoritmoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlgoritmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioLouvain)
                    .addComponent(radioGirvan)
                    .addComponent(radioClique)
                    .addGroup(panelAlgoritmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEjecutar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAlgoritmoLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtValorP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(tabsAlgoritmo)
                .addContainerGap())
        );
        panelAlgoritmoLayout.setVerticalGroup(
            panelAlgoritmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlgoritmoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(radioLouvain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioGirvan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioClique)
                .addGap(28, 28, 28)
                .addGroup(panelAlgoritmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEjecutar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelAlgoritmoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabsAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsPrincipal.addTab("Algoritmo", panelAlgoritmo);

        jLabel18.setText("Categoria:");

        jLabel19.setText("Comunidad:");

        txtAddRmvCom.setText("Nombre Comunidad");

        btnAddCatToCom.setText("+");
        btnAddCatToCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCatToComActionPerformed(evt);
            }
        });

        btnRmvCatFromCom.setText("-");
        btnRmvCatFromCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvCatFromComActionPerformed(evt);
            }
        });

        btnAddComToSet.setText("+");
        btnAddComToSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddComToSetActionPerformed(evt);
            }
        });

        btnRmvComFromSet.setText("-");
        btnRmvComFromSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvComFromSetActionPerformed(evt);
            }
        });

        btnListComFromSet.setText("Listar");
        btnListComFromSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListComFromSetActionPerformed(evt);
            }
        });

        btnShowSet.setText("Visualizar");
        btnShowSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSetActionPerformed(evt);
            }
        });

        btnExportSet.setText("Exportar");
        btnExportSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportSetActionPerformed(evt);
            }
        });

        txtCatAddRmvSet.setText("Categoria");

        txtComToAddRmvCat.setText("Comunidad");

        txtComToList.setText("Nombre comunidad");

        btnListCatFromCom.setText("Listar");
        btnListCatFromCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCatFromComActionPerformed(evt);
            }
        });

        comboTipoSet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Creado", "Importado" }));

        jLabel15.setText("AÑADIR/QUITAR");

        jLabel16.setText("CAMBIAR NOMBRE");

        txtNombreAnterior.setText("Anterior");

        txtNombreNuevo.setText("Nuevo");

        btnChangeNameSet.setText("OK");
        btnChangeNameSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeNameSetActionPerformed(evt);
            }
        });

        jLabel26.setText("VER CONJUNTO DE COMUNIDADES");

        jLabel27.setText("VER COMUNIDAD");

        btnShowCom.setText("Visualizar");
        btnShowCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowComActionPerformed(evt);
            }
        });

        comboTipoNombreSet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Conjunto", "Comunidad", "Categoria" }));
        comboTipoNombreSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoNombreSetActionPerformed(evt);
            }
        });

        txtListSet.setColumns(20);
        txtListSet.setRows(5);
        jScrollPane5.setViewportView(txtListSet);

        javax.swing.GroupLayout panelComunidadesLayout = new javax.swing.GroupLayout(panelComunidades);
        panelComunidades.setLayout(panelComunidadesLayout);
        panelComunidadesLayout.setHorizontalGroup(
            panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComunidadesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExportSet, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipoSet, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelComunidadesLayout.createSequentialGroup()
                        .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelComunidadesLayout.createSequentialGroup()
                                .addComponent(comboTipoNombreSet, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelComunidadesLayout.createSequentialGroup()
                                .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelComunidadesLayout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCatAddRmvSet, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtComToAddRmvCat, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelComunidadesLayout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAddRmvCom, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddCatToCom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddComToSet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnChangeNameSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRmvCatFromCom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRmvComFromSet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelComunidadesLayout.createSequentialGroup()
                        .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComToList, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListCatFromCom, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListComFromSet, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnShowCom, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowSet, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelComunidadesLayout.setVerticalGroup(
            panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComunidadesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(panelComunidadesLayout.createSequentialGroup()
                        .addComponent(comboTipoSet, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelComunidadesLayout.createSequentialGroup()
                                .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(btnAddCatToCom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCatAddRmvSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtComToAddRmvCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(txtAddRmvCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddComToSet, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombreAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboTipoNombreSet, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelComunidadesLayout.createSequentialGroup()
                                .addComponent(btnRmvCatFromCom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRmvComFromSet, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(btnChangeNameSet, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnListComFromSet, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(btnShowSet, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnShowCom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnListCatFromCom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelComunidadesLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(txtComToList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(btnExportSet)))
                .addContainerGap())
        );

        tabsPrincipal.addTab("Conjunto", panelComunidades);

        txtListGraph1.setColumns(20);
        txtListGraph1.setRows(5);
        jScrollPane6.setViewportView(txtListGraph1);

        btnCompararComunidades.setText("Comparar");

        comboTipoCom1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Importado", "Creado" }));

        comboTipoCom2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Importado", "Creado" }));

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jLabel17.setText("Comparar 2 comunidades");

        jLabel20.setText("Comparar 2 conjuntos");

        btnCompararConjuntos.setText("Comparar");

        javax.swing.GroupLayout panelComparacionLayout = new javax.swing.GroupLayout(panelComparacion);
        panelComparacion.setLayout(panelComparacionLayout);
        panelComparacionLayout.setHorizontalGroup(
            panelComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComparacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelComparacionLayout.createSequentialGroup()
                        .addGroup(panelComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboTipoCom1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboTipoCom2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(panelComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(jTextField2))
                        .addGap(18, 18, 18)
                        .addComponent(btnCompararComunidades, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompararConjuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelComparacionLayout.setVerticalGroup(
            panelComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComparacionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComparacionLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(22, 22, 22)
                        .addGroup(panelComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTipoCom1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTipoCom2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCompararComunidades, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(btnCompararConjuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabsPrincipal.addTab("Comparación", panelComparacion);

        menuFichero.setText("Fichero");

        mItemImportarGrafo.setText("Importar grafo");
        mItemImportarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemImportarGrafoActionPerformed(evt);
            }
        });
        menuFichero.add(mItemImportarGrafo);

        mItemImportarSet.setText("Importar conjunto");
        menuFichero.add(mItemImportarSet);

        mItemExportarGrafo.setText("Exportar grafo");
        menuFichero.add(mItemExportarGrafo);

        mItemExportarSet.setText("Exportar conjunto");
        menuFichero.add(mItemExportarSet);

        mItemSalir.setText("Salir");
        mItemSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mItemSalirMouseClicked(evt);
            }
        });
        mItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSalirActionPerformed(evt);
            }
        });
        menuFichero.add(mItemSalir);

        barraMenu.add(menuFichero);

        menuEditar.setText("Editar");

        mItemNuevoGrafo.setText("Nuevo grafo");
        mItemNuevoGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemNuevoGrafoActionPerformed(evt);
            }
        });
        menuEditar.add(mItemNuevoGrafo);

        barraMenu.add(menuEditar);

        menuAyuda.setText("Ayuda");

        mItemManual.setText("Manual");
        mItemManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemManualActionPerformed(evt);
            }
        });
        menuAyuda.add(mItemManual);

        mItemAbout.setText("Acerca de...");
        mItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAboutActionPerformed(evt);
            }
        });
        menuAyuda.add(mItemAbout);

        barraMenu.add(menuAyuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsPrincipal)
        );

        tabsPrincipal.setEnabledAt(1, false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorPActionPerformed

    private void ckTodasPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckTodasPaginasActionPerformed
        if (ckTodasPaginas.isSelected()) listPaginas.setSelectionInterval(0, listPaginas.getModel().getSize() - 1); 
        else listPaginas.clearSelection();
    }//GEN-LAST:event_ckTodasPaginasActionPerformed

    private void mItemImportarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemImportarGrafoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mItemImportarGrafoActionPerformed

    private void comboTipoEnlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoEnlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoEnlaceActionPerformed

    private void btnListCatGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCatGraphActionPerformed
        iCtrlPresentacion.mostrarGrafoCat();
    }//GEN-LAST:event_btnListCatGraphActionPerformed

    private void btnListPagGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPagGraphActionPerformed
        iCtrlPresentacion.mostrarGrafoPag();
    }//GEN-LAST:event_btnListPagGraphActionPerformed

    private void btnListLinksGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListLinksGraphActionPerformed
        iCtrlPresentacion.mostrarGrafoEnlaces();
    }//GEN-LAST:event_btnListLinksGraphActionPerformed

    private void btnExportarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarGrafoActionPerformed
        //iCtrlPresentacion.exportarGrafo();
    }//GEN-LAST:event_btnExportarGrafoActionPerformed

    private void btnListCatFromComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCatFromComActionPerformed
        iCtrlPresentacion.mostrarCom(txtComToList.getText(), comboTipoSet.getSelectedIndex() != 0);
    }//GEN-LAST:event_btnListCatFromComActionPerformed

    private void btnExportSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportSetActionPerformed
        //iCtrlPresentacion.exportarConjunto();
    }//GEN-LAST:event_btnExportSetActionPerformed

    private void btnShowSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowSetActionPerformed

    private void btnListComFromSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListComFromSetActionPerformed
        iCtrlPresentacion.mostrarCto(comboTipoSet.getSelectedIndex() != 0);
    }//GEN-LAST:event_btnListComFromSetActionPerformed

    private void btnShowComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowComActionPerformed

    private void mItemSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mItemSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mItemSalirMouseClicked

    private void mItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mItemSalirActionPerformed

    private void mItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAboutActionPerformed
       iCtrlPresentacion.sincronizacionVistaPrincipal_a_About();
    }//GEN-LAST:event_mItemAboutActionPerformed

    private void radioGirvanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGirvanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioGirvanActionPerformed

    private void btnAddCatToGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCatToGraphActionPerformed
        iCtrlPresentacion.addGrafoCat(txtCatToAddRmv.getText());
    }//GEN-LAST:event_btnAddCatToGraphActionPerformed

    private void btnImportarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarGrafoActionPerformed
        iCtrlPresentacion.sincronizacionVistaPrincipal_a_FileChooser(false);
        //iCtrlPresentacion.importarGrafo(null);
        tabsPrincipal.setEnabledAt(1, true);
        tabsPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_btnImportarGrafoActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        int a = 0;
        if(radioGirvan.isSelected()) a = 1;
        else if(radioClique.isSelected()) a = 2;
        
        iCtrlPresentacion.ejecutar(a, Integer.parseInt(txtValorP.getText()));          
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void comboTipoNombreSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoNombreSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoNombreSetActionPerformed

    private void btnImportarGrafo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarGrafo1ActionPerformed
        iCtrlPresentacion.importarGrafo(null);
    }//GEN-LAST:event_btnImportarGrafo1ActionPerformed

    private void btnNuevoGrafo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoGrafo1ActionPerformed
        iCtrlPresentacion.crearGrafo();
    }//GEN-LAST:event_btnNuevoGrafo1ActionPerformed

    private void btnNuevoGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoGrafoActionPerformed
        iCtrlPresentacion.crearGrafo();
        tabsPrincipal.setEnabledAt(1, true);
        tabsPrincipal.setSelectedIndex(1);        
    }//GEN-LAST:event_btnNuevoGrafoActionPerformed

    private void mItemNuevoGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemNuevoGrafoActionPerformed
        iCtrlPresentacion.crearGrafo();
        tabsPrincipal.setEnabledAt(1, true);
        tabsPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_mItemNuevoGrafoActionPerformed

    private void txtCatToAddRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatToAddRmvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatToAddRmvActionPerformed

    private void txtPagToAddRmvFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPagToAddRmvFocusGained
        
    }//GEN-LAST:event_txtPagToAddRmvFocusGained

    private void ckTodasCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckTodasCategoriasActionPerformed
        if (ckTodasCategorias.isSelected()) listCategorias.setSelectionInterval(0, listCategorias.getModel().getSize() - 1); 
        else listCategorias.clearSelection();
    }//GEN-LAST:event_ckTodasCategoriasActionPerformed

    private void btnAplicarSelPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarSelPagActionPerformed
        List l = listPaginas.getSelectedValuesList(); 
        ArrayList<String> al = new ArrayList<>(l);
        iCtrlPresentacion.aplicarSelPag(al);
       // ArrayList<String> listData = new ArrayList<String>();
       // listData.add("Elem1");
       // listData.add("Elem2");
       // listData.add("Elem3");
       // listData.add("Elem4");
       // listPaginas.setListData(listData.toArray());
        
    }//GEN-LAST:event_btnAplicarSelPagActionPerformed

    private void btnAplicarSelCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarSelCatActionPerformed
        List l = listCategorias.getSelectedValuesList(); 
        ArrayList<String> al = new ArrayList<>(l);
        //System.out.println(al);
        iCtrlPresentacion.aplicarSelCat(al);
    }//GEN-LAST:event_btnAplicarSelCatActionPerformed

    private void btnAplicarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarFiltrosActionPerformed
        String name = spNombre.getValue().toString();
        String pagComun = spPagComun.getValue().toString();
        String catComun = spCatComun.getValue().toString();
        String superComun = spSuperComun.getValue().toString();
        String subComun = spSubComun.getValue().toString();
        //System.out.println(name+","+pagComun+","+catComun+","+superComun+","+subComun);
        iCtrlPresentacion.aplicarFiltros(name+","+pagComun+","+catComun+","+superComun+","+subComun);
    }//GEN-LAST:event_btnAplicarFiltrosActionPerformed

    private void btnImportarConjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarConjActionPerformed
        //iCtrlPresentacion.importarConjunto(null);
        tabsPrincipal.setSelectedIndex(3);
    }//GEN-LAST:event_btnImportarConjActionPerformed

    private void btnChangeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeNameActionPerformed
        iCtrlPresentacion.modGrafoNombre(txtNombreNodoAnterior.getText(), txtNombreNodoNuevo.getText(), comboTipoNodo.getSelectedIndex() != 0);
    }//GEN-LAST:event_btnChangeNameActionPerformed

    private void btnRmvCatFromGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvCatFromGraphActionPerformed
        iCtrlPresentacion.rmvGrafoCat(txtCatToAddRmv.getText());
    }//GEN-LAST:event_btnRmvCatFromGraphActionPerformed

    private void btnAddPagToGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPagToGraphActionPerformed
        iCtrlPresentacion.addGrafoPag(txtPagToAddRmv.getText());
    }//GEN-LAST:event_btnAddPagToGraphActionPerformed

    private void btnRmvPagFromGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvPagFromGraphActionPerformed
        iCtrlPresentacion.rmvGrafoPag(txtPagToAddRmv.getText());
    }//GEN-LAST:event_btnRmvPagFromGraphActionPerformed

    private void btnAddLinkToGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLinkToGraphActionPerformed
        iCtrlPresentacion.addGrafoEnlace(txtNodo1Enlace.getText(), txtNodo2Enlace.getText(), comboTipoEnlace.getSelectedItem().toString());        
    }//GEN-LAST:event_btnAddLinkToGraphActionPerformed

    private void btnRmvLinkFromGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvLinkFromGraphActionPerformed
        iCtrlPresentacion.rmvGrafoEnlace(txtNodo1Enlace.getText(), txtNodo2Enlace.getText(), comboTipoEnlace.getSelectedItem().toString());
    }//GEN-LAST:event_btnRmvLinkFromGraphActionPerformed

    private void btnAddCatToComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCatToComActionPerformed
        iCtrlPresentacion.addCtoCat(txtCatAddRmvSet.getText(), txtComToAddRmvCat.getText(), comboTipoSet.getSelectedIndex() != 0);
    }//GEN-LAST:event_btnAddCatToComActionPerformed

    private void btnRmvCatFromComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvCatFromComActionPerformed
        iCtrlPresentacion.rmvCtoCat(txtCatAddRmvSet.getText(), txtComToAddRmvCat.getText(), comboTipoSet.getSelectedIndex() != 0);
    }//GEN-LAST:event_btnRmvCatFromComActionPerformed

    private void btnAddComToSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddComToSetActionPerformed
        iCtrlPresentacion.addCtoCom(txtAddRmvCom.getText(), comboTipoSet.getSelectedIndex() != 0);
    }//GEN-LAST:event_btnAddComToSetActionPerformed

    private void btnRmvComFromSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvComFromSetActionPerformed
        iCtrlPresentacion.rmvCtoCom(txtAddRmvCom.getText(), comboTipoSet.getSelectedIndex() != 0);
    }//GEN-LAST:event_btnRmvComFromSetActionPerformed

    private void btnChangeNameSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeNameSetActionPerformed
        iCtrlPresentacion.modCtoNombre(comboTipoNombreSet.getSelectedIndex(), txtNombreAnterior.getText(), txtNombreNuevo.getText(), comboTipoSet.getSelectedIndex() != 0);
    }//GEN-LAST:event_btnChangeNameSetActionPerformed

    private void comboTipoNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoNodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoNodoActionPerformed

    private void mItemManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemManualActionPerformed
       iCtrlPresentacion.sincronizacionVistaPrincipal_a_Manual();
    }//GEN-LAST:event_mItemManualActionPerformed

 //   /**
 //    * @param args the command line arguments
 //    */
    
    
 //   public static void main(String args[]) {
 //       /* Set the Nimbus look and feel */
 //       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 //      try {
 //           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
 //               if ("Nimbus".equals(info.getName())) {
 //                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
 //                   break;
 //               }
 //          }
 //       } catch (ClassNotFoundException ex) {
 //           java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  //      } catch (InstantiationException ex) {
  //          java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  //      } catch (IllegalAccessException ex) {
  //          java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  //      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
  //          java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 //       }
        //</editor-fold>
  //      //</editor-fold>
//        /* Create and display the form */
  //      java.awt.EventQueue.invokeLater(new Runnable() {
    //        public void run() {
      //          new VistaPrincipal().setVisible(true);
       //     }
   //     });
  //  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnAddCatToCom;
    private javax.swing.JButton btnAddCatToGraph;
    private javax.swing.JButton btnAddComToSet;
    private javax.swing.JButton btnAddLinkToGraph;
    private javax.swing.JButton btnAddPagToGraph;
    private javax.swing.JButton btnAplicarFiltros;
    private javax.swing.JButton btnAplicarSelCat;
    private javax.swing.JButton btnAplicarSelPag;
    private javax.swing.JButton btnChangeName;
    private javax.swing.JButton btnChangeNameSet;
    private javax.swing.JButton btnCompararComunidades;
    private javax.swing.JButton btnCompararConjuntos;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnExportSet;
    private javax.swing.JButton btnExportarGrafo;
    private javax.swing.JButton btnImportarConj;
    private javax.swing.JButton btnImportarGrafo;
    private javax.swing.JButton btnImportarGrafo1;
    private javax.swing.JButton btnListCatFromCom;
    private javax.swing.JButton btnListCatGraph;
    private javax.swing.JButton btnListComFromSet;
    private javax.swing.JButton btnListLinksGraph;
    private javax.swing.JButton btnListPagGraph;
    private javax.swing.JButton btnNuevoGrafo;
    private javax.swing.JButton btnNuevoGrafo1;
    private javax.swing.JButton btnRmvCatFromCom;
    private javax.swing.JButton btnRmvCatFromGraph;
    private javax.swing.JButton btnRmvComFromSet;
    private javax.swing.JButton btnRmvLinkFromGraph;
    private javax.swing.JButton btnRmvPagFromGraph;
    private javax.swing.JButton btnShowCom;
    private javax.swing.JButton btnShowSet;
    private javax.swing.JCheckBox ckTodasCategorias;
    private javax.swing.JCheckBox ckTodasPaginas;
    private javax.swing.JComboBox comboTipoCom1;
    private javax.swing.JComboBox comboTipoCom2;
    private javax.swing.JComboBox comboTipoEnlace;
    private javax.swing.JComboBox comboTipoNodo;
    private javax.swing.JComboBox comboTipoNombreSet;
    private javax.swing.JComboBox comboTipoSet;
    private javax.swing.ButtonGroup grupoAlgoritmos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JList listCategorias;
    private javax.swing.JList listPaginas;
    private javax.swing.JMenuItem mItemAbout;
    private javax.swing.JMenuItem mItemExportarGrafo;
    private javax.swing.JMenuItem mItemExportarSet;
    private javax.swing.JMenuItem mItemImportarGrafo;
    private javax.swing.JMenuItem mItemImportarSet;
    private javax.swing.JMenuItem mItemManual;
    private javax.swing.JMenuItem mItemNuevoGrafo;
    private javax.swing.JMenuItem mItemSalir;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuFichero;
    private javax.swing.JPanel panelAlgoritmo;
    private javax.swing.JPanel panelComparacion;
    private javax.swing.JPanel panelComunidades;
    private javax.swing.JPanel panelGrafo;
    private javax.swing.JPanel panelImportar;
    private javax.swing.JRadioButton radioClique;
    private javax.swing.JRadioButton radioGirvan;
    private javax.swing.JRadioButton radioLouvain;
    private javax.swing.JSpinner spCatComun;
    private javax.swing.JSpinner spNombre;
    private javax.swing.JSpinner spPagComun;
    private javax.swing.JSpinner spSubComun;
    private javax.swing.JSpinner spSuperComun;
    private javax.swing.JPanel tabFiltros;
    private javax.swing.JPanel tabSelCat;
    private javax.swing.JPanel tabSelPag;
    private javax.swing.JTabbedPane tabsAlgoritmo;
    private javax.swing.JTabbedPane tabsPrincipal;
    private javax.swing.JTextField txtAddRmvCom;
    private javax.swing.JTextField txtCatAddRmvSet;
    private javax.swing.JTextField txtCatToAddRmv;
    private javax.swing.JTextField txtComToAddRmvCat;
    private javax.swing.JTextField txtComToList;
    private javax.swing.JTextArea txtListGraph;
    private javax.swing.JTextArea txtListGraph1;
    private javax.swing.JTextArea txtListSet;
    private javax.swing.JTextField txtNodo1Enlace;
    private javax.swing.JTextField txtNodo2Enlace;
    private javax.swing.JTextField txtNombreAnterior;
    private javax.swing.JTextField txtNombreNodoAnterior;
    private javax.swing.JTextField txtNombreNodoNuevo;
    private javax.swing.JTextField txtNombreNuevo;
    private javax.swing.JTextField txtPagToAddRmv;
    private javax.swing.JTextField txtValorP;
    // End of variables declaration//GEN-END:variables
}
